### ISSUE TITLE
Bodonyi/flask - requirements.txt contains curses which can't be installed with pip

### ISSUE THREAD

**Issue by alexkallai** [M0Rph3U56031769/pythonbasic#89]
error message:

(venv) D:\GIT\_private_projects\pythonbasic\Bodonyi\flask>pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement curses (from versions: none)
ERROR: No matching distribution found for curses
WARNING: You are using pip version 21.1.1; however, version 23.1.2 is available.
You should consider upgrading via the 'd:\git\_private_projects\pythonbasic\bodonyi\flask\venv\scripts\python.exe -m pip install --upgrade pip' command.

(venv) D:\GIT\_private_projects\pythonbasic\Bodonyi\flask>pip install curses
ERROR: Could not find a version that satisfies the requirement curses (from versions: none)
ERROR: No matching distribution found for curses
WARNING: You are using pip version 21.1.1; however, version 23.1.2 is available.
You should consider upgrading via the 'd:\git\_private_projects\pythonbasic\bodonyi\flask\venv\scripts\python.exe -m pip install --upgrade pip' command.

**Comment by M0Rph3U56031769** [comment]
```sh
(venv) D:\GIT_private_projects\pythonbasic\Bodonyi\flask>pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement curses (from versions: none)
ERROR: No matching distribution found for curses
WARNING: You are using pip version 21.1.1; however, version 23.1.2 is available.
You should consider upgrading via the 'd:\git_private_projects\pythonbasic\bodonyi\flask\venv\scripts\python.exe -m pip install --upgrade pip' command.

(venv) D:\GIT_private_projects\pythonbasic\Bodonyi\flask>pip install curses
ERROR: Could not find a version that satisfies the requirement curses (from versions: none)
ERROR: No matching distribution found for curses
WARNING: You are using pip version 21.1.1; however, version 23.1.2 is available.
You should consider upgrading via the 'd:\git_private_projects\pythonbasic\bodonyi\flask\venv\scripts\python.exe -m pip install --upgrade pip' command.
```

**Comment by M0Rph3U56031769** [comment]
2p - function
